### ISSUE TITLE
Keras_ocr TfLite version error.

### ISSUE THREAD

**Issue by parameswar-ds** [tulasiram58827/ocr_tflite#1]
hi @tulasiram58827 ,
I'm able to convert keras_ocr into TfLite version with your repo, but it is not detecting numbers correctly.
Im using ocr_float16.tflite.

PFA of a test image.

![test](https://user-images.githubusercontent.com/63809888/104000472-4e0f5680-51c4-11eb-845f-0c2d6afd05f1.png)

**Comment by tulasiram58827** [comment]
@parameswar-ds  Can you send the input image

**Comment by parameswar-ds** [comment]
here it is

![808](https://user-images.githubusercontent.com/63809888/104003064-efe47280-51c7-11eb-98d2-034fafdbd1fd.jpg)

**Comment by tulasiram58827** [comment]
It seems like there is some bug. Let me debug this weekend.

**Comment by parameswar-ds** [comment]
Ok

**Comment by tulasiram58827** [comment]
Hey @parameswar-ds Sorry for the delay. I think the problem is with CTC decoder. Can you try with V1 model which does not contain CTC Decoder

**Comment by parameswararao-13** [comment]
@tulasiram58827 
Problem is in preprocessing steps, 
It's working for me then.

**Comment by parameswar-ds** [comment]
you can find it here[https://github.com/parameswar-ds/KERAS_OCR_TRT_CONVERSION/blob/main/keras_ocr_TRT_conversion.ipynb](url)

**Comment by parameswar-ds** [comment]
you can get it here,
[https://github.com/parameswar-ds/KERAS_OCR_TRT_CONVERSION.git](url)

**Comment by tulasiram58827** [comment]
It looks like you have used portion of code from my notebooks. But you have nowhere mentioned references. It's good practice to mention about references when you used the others code.

**Comment by tulasiram58827** [comment]
If you found the bug can you open a PR with the updated code
